package domain.entities.EstrategiasNotificacion.EstrategiaEmail;


import domain.entities.Contacto;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;

public class EstrategiaMailtrapAdapter implements EmailAdapterInterface {

    @Override
    public void notificarViaEmail(String asunto, String mensaje, Contacto contacto) {
        String to = contacto.getEmail();
        final String from = "info@patitas.com.ar";
        final String username = System.getenv("MAILTRAP_USERNAME");;//username generated by Mailtrap
        final String password =System.getenv("MAILTRAP_PASSWORD");//password generated by Mailtrap
        System.out.println(username);
        System.out.println(password);
        String host = "smtp.mailtrap.io";
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "2525");

        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(to));
            message.setSubject(asunto);
            message.setText(mensaje);
            Transport.send(message);
            System.out.println("Sent message successfully");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }
}
